networks:
  default:
    name: sail
    driver: overlay
    attachable: true

services:
  statamic-prod:
    image: skulpture/brittle-systems
    restart: unless-stopped
    extra_hosts:
      - host.docker.internal:host-gateway
    entrypoint: bash
    command: >
      -c "
       touch .env &&
       php artisan optimize:clear &&
       php artisan optimize &&
       # build frontend
       pnpm install &&
       pnpm build &&
       # see `start-container`
       /usr/bin/supervisord -c /etc/supervisor/conf.d/supervisord.conf"
    environment:
      WWWUSER: ${WWWUSER}
      LARAVEL_SAIL: 1
      XDEBUG_MODE: ${SAIL_XDEBUG_MODE:-off}
      XDEBUG_CONFIG: ${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}
      IGNITION_LOCAL_SITES_PATH: ${PWD}
      APP_KEY: ${APP_KEY}
      APP_TIMEZONE: ${APP_TIMEZONE}
      SESSION_DOMAIN: ${SESSION_DOMAIN}
      CACHE_STORE: ${CACHE_STORE}
      APP_URL: https://brittle.systems
      DB_CONECTION: ${DB_CONECTION}
      DATABASE_URL: ${DATABASE_URL}
      APP_MAINTENANCE_DRIVER: ${APP_MAINTENANCE_DRIVER}
      APP_DEBUG: false
      SESSION_ENCRYPT: ${SESSION_ENCRYPT}
      STATAMIC_API_ENABLED: ${STATAMIC_API_ENABLED}
      LOG_LEVEL: ${LOG_LEVEL}
      VITE_APP_NAME: ${APP_NAME}
      APP_ENV: production
      STATAMIC_OAUTH_ENABLED: true
      OAUTH_KEYCLOAK_CLIENT_ID: ${OAUTH_KEYCLOAK_CLIENT_ID}
      OAUTH_KEYCLOAK_CLIENT_SECRET: ${OAUTH_KEYCLOAK_CLIENT_SECRET}
    volumes:
      - ~/brittle-systems-master/statamic:/var/www/html
    deploy:
      mode: replicated
      replicas: 1
    ulimits:
      nofile:
        soft: 20000
        hard: 20000
  statamic-dev:
    image: skulpture/brittle-systems:dev
    restart: unless-stopped
    extra_hosts:
      - host.docker.internal:host-gateway
    entrypoint: bash
    command: >
      -c "
       touch .env &&
       php artisan optimize:clear &&
       php artisan optimize &&
       # build frontend
       pnpm install &&
       pnpm build &&
       # see `start-container`
       /usr/bin/supervisord -c /etc/supervisor/conf.d/supervisord.conf"
    environment:
      WWWUSER: ${WWWUSER}
      LARAVEL_SAIL: 1
      XDEBUG_MODE: ${SAIL_XDEBUG_MODE:-off}
      XDEBUG_CONFIG: ${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}
      IGNITION_LOCAL_SITES_PATH: ${PWD}
      APP_KEY: ${APP_KEY}
      APP_TIMEZONE: ${APP_TIMEZONE}
      SESSION_DOMAIN: ${SESSION_DOMAIN}
      CACHE_STORE: ${CACHE_STORE}
      APP_URL: https://dev.brittle.systems
      DB_CONECTION: ${DB_CONECTION}
      DATABASE_URL: ${DATABASE_URL}
      APP_MAINTENANCE_DRIVER: ${APP_MAINTENANCE_DRIVER}
      APP_DEBUG: true
      SESSION_ENCRYPT: ${SESSION_ENCRYPT}
      STATAMIC_API_ENABLED: ${STATAMIC_API_ENABLED}
      LOG_LEVEL: ${LOG_LEVEL}
      VITE_APP_NAME: ${APP_NAME}
      APP_ENV: development
      STATAMIC_OAUTH_ENABLED: true
      OAUTH_KEYCLOAK_CLIENT_ID: ${OAUTH_KEYCLOAK_CLIENT_ID}
      OAUTH_KEYCLOAK_CLIENT_SECRET: ${OAUTH_KEYCLOAK_CLIENT_SECRET}
    volumes:
      - ~/brittle-systems-dev/statamic:/var/www/html
    deploy:
      mode: replicated
      replicas: 1
    ulimits:
      nofile:
        soft: 20000
        hard: 20000
