networks:
  default:
    name: sail
    driver: overlay
    attachable: true

services:
  statamic:
    image: skulpture/brittle-systems:${TAG:-latest}
    environment:
      WWWUSER: ${WWWUSER}
      LARAVEL_SAIL: 1
      XDEBUG_MODE: ${SAIL_XDEBUG_MODE:-off}
      XDEBUG_CONFIG: ${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}
      IGNITION_LOCAL_SITES_PATH: ${PWD}
    volumes:
      - .:/var/www/html
    deploy:
      mode: replicated
      replicas: 1
    ulimits:
      soft: 20000
      hard: 20000
