name: Build services

on:
  pull_request:
    branches: [master, staging, dev]
  workflow_dispatch:

env:
  BRANCH_NAME: ${{ github.base_ref || github.ref_name }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: "Install dependencies: brittle-systems"
        run: |
          # https://laravel.com/docs/11.x/sail#installing-composer-dependencies-for-existing-projects
          
          docker run --rm \
            -u "$(id -u):$(id -g)" \
            -v "./statamic:/var/www/html" \
            -w /var/www/html \
            laravelsail/php83-composer:latest \
            composer install --ignore-platform-reqs
            
      - name: "Build Docker image: brittle-systems"
        uses: docker/build-push-action@v5
        env:
          TAG: ${{ (env.BRANCH_NAME == 'master' && 'latest') || env.BRANCH_NAME }}
        with:
          context: "{{defaultContext}}:api"
          platforms: linux/amd64,linux/arm64
          push: false
          tags: |
            skulpture/brittle-systems:${{ env.TAG }}
