name: Preview infrastructure

on:
  pull_request:
    branches: [master, staging, dev]
  workflow_dispatch:

env:
  BRANCH_NAME: ${{ github.base_ref || github.ref_name }}

jobs:
  preview:
    permissions:
      contents: read
      id-token: write
      pull-requests: write

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: stable

      - name: "Install dependencies: infrastructure"
        run: go mod download
        working-directory: "infrastructure"

      - name: "Preview stack: skulpture/brittle-systems"
        uses: pulumi/actions@v5
        with:
          command: preview
          stack-name: "skulpture/brittle-systems/statamic"
          comment-on-pr: true
          github-token: ${{ secrets.GITHUB_TOKEN }}
          work-dir: "infrastructure"
          upsert: true
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
          COMPUTE_INSTANCE_NAME: "brittle-systems"
          CLOUDFLARE_ZONE_ID: ${{ vars.CLOUDFLARE_ZONE_ID }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          DO_SSH_PUBLIC_KEY: ${{ vars.DO_SSH_PUBLIC_KEY }}
          DIGITALOCEAN_TOKEN: ${{ secrets.DIGITALOCEAN_TOKEN }}
